### ISSUE TITLE
Gen 2 power can go negative

### ISSUE THREAD

**Issue by barrown** [reading-hydro/readinghydro.com#3]
Since about 14:30 yesterday, the API for Gen 2 power output went negative:
![image](https://github.com/user-attachments/assets/6644f44f-05c7-41b4-9df0-8c0eae876eaa)

Is this a calibration issue or expected behaviour for the API and I just need to filter the input?

**Comment by xplora1a** [comment]
We had to shut down yesterday, and so not generating, what you are seeing is the parasitic loads in the Turbine House, Control System, fans, etc that have to operate event when we are not generating. 400W looks about right.

**Comment by xplora1a** [comment]
I like your graph, is this published somewhere?

**Comment by xplora1a** [comment]
On our website we filter out negative values.

**Comment by xplora1a** [comment]
Thanks

**Comment by barrown** [comment]
> We had to shut down yesterday, and so not generating, what you are seeing is the parasitic loads in the Turbine House, Control System, fans, etc that have to operate event when we are not generating. 400W looks about right.

Ah! That's really interesting... so it's actually informative data and not a glitch! Thank you Stuart!

My graph is from my instance of https://www.home-assistant.io/ so not published anywhere. I have a whole dashboard for your hydro plant!
![image](https://github.com/user-attachments/assets/73d5a69c-de6b-4235-b009-aa585e208bca)
